//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonTCGApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class Generations : global::System.Configuration.ApplicationSettingsBase {
        
        private static Generations defaultInstance = ((Generations)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Generations())));
        
        public static Generations Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_0 {
            get {
                return ((string)(this["PKMN_0"]));
            }
            set {
                this["PKMN_0"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_1 {
            get {
                return ((string)(this["PKMN_1"]));
            }
            set {
                this["PKMN_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_2 {
            get {
                return ((string)(this["PKMN_2"]));
            }
            set {
                this["PKMN_2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_3 {
            get {
                return ((string)(this["PKMN_3"]));
            }
            set {
                this["PKMN_3"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_4 {
            get {
                return ((string)(this["PKMN_4"]));
            }
            set {
                this["PKMN_4"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_5 {
            get {
                return ((string)(this["PKMN_5"]));
            }
            set {
                this["PKMN_5"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_6 {
            get {
                return ((string)(this["PKMN_6"]));
            }
            set {
                this["PKMN_6"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_7 {
            get {
                return ((string)(this["PKMN_7"]));
            }
            set {
                this["PKMN_7"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_8 {
            get {
                return ((string)(this["PKMN_8"]));
            }
            set {
                this["PKMN_8"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_9 {
            get {
                return ((string)(this["PKMN_9"]));
            }
            set {
                this["PKMN_9"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_10 {
            get {
                return ((string)(this["PKMN_10"]));
            }
            set {
                this["PKMN_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_11 {
            get {
                return ((string)(this["PKMN_11"]));
            }
            set {
                this["PKMN_11"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_12 {
            get {
                return ((string)(this["PKMN_12"]));
            }
            set {
                this["PKMN_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_13 {
            get {
                return ((string)(this["PKMN_13"]));
            }
            set {
                this["PKMN_13"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_14 {
            get {
                return ((string)(this["PKMN_14"]));
            }
            set {
                this["PKMN_14"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_15 {
            get {
                return ((string)(this["PKMN_15"]));
            }
            set {
                this["PKMN_15"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_16 {
            get {
                return ((string)(this["PKMN_16"]));
            }
            set {
                this["PKMN_16"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_17 {
            get {
                return ((string)(this["PKMN_17"]));
            }
            set {
                this["PKMN_17"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_18 {
            get {
                return ((string)(this["PKMN_18"]));
            }
            set {
                this["PKMN_18"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_19 {
            get {
                return ((string)(this["PKMN_19"]));
            }
            set {
                this["PKMN_19"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_20 {
            get {
                return ((string)(this["PKMN_20"]));
            }
            set {
                this["PKMN_20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_21 {
            get {
                return ((string)(this["PKMN_21"]));
            }
            set {
                this["PKMN_21"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_22 {
            get {
                return ((string)(this["PKMN_22"]));
            }
            set {
                this["PKMN_22"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_23 {
            get {
                return ((string)(this["PKMN_23"]));
            }
            set {
                this["PKMN_23"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_24 {
            get {
                return ((string)(this["PKMN_24"]));
            }
            set {
                this["PKMN_24"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_25 {
            get {
                return ((string)(this["PKMN_25"]));
            }
            set {
                this["PKMN_25"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_26 {
            get {
                return ((string)(this["PKMN_26"]));
            }
            set {
                this["PKMN_26"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_27 {
            get {
                return ((string)(this["PKMN_27"]));
            }
            set {
                this["PKMN_27"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_28 {
            get {
                return ((string)(this["PKMN_28"]));
            }
            set {
                this["PKMN_28"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_29 {
            get {
                return ((string)(this["PKMN_29"]));
            }
            set {
                this["PKMN_29"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_30 {
            get {
                return ((string)(this["PKMN_30"]));
            }
            set {
                this["PKMN_30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_31 {
            get {
                return ((string)(this["PKMN_31"]));
            }
            set {
                this["PKMN_31"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_32 {
            get {
                return ((string)(this["PKMN_32"]));
            }
            set {
                this["PKMN_32"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_33 {
            get {
                return ((string)(this["PKMN_33"]));
            }
            set {
                this["PKMN_33"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_34 {
            get {
                return ((string)(this["PKMN_34"]));
            }
            set {
                this["PKMN_34"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_35 {
            get {
                return ((string)(this["PKMN_35"]));
            }
            set {
                this["PKMN_35"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_36 {
            get {
                return ((string)(this["PKMN_36"]));
            }
            set {
                this["PKMN_36"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_37 {
            get {
                return ((string)(this["PKMN_37"]));
            }
            set {
                this["PKMN_37"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_38 {
            get {
                return ((string)(this["PKMN_38"]));
            }
            set {
                this["PKMN_38"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_39 {
            get {
                return ((string)(this["PKMN_39"]));
            }
            set {
                this["PKMN_39"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_40 {
            get {
                return ((string)(this["PKMN_40"]));
            }
            set {
                this["PKMN_40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_41 {
            get {
                return ((string)(this["PKMN_41"]));
            }
            set {
                this["PKMN_41"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_42 {
            get {
                return ((string)(this["PKMN_42"]));
            }
            set {
                this["PKMN_42"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_43 {
            get {
                return ((string)(this["PKMN_43"]));
            }
            set {
                this["PKMN_43"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_44 {
            get {
                return ((string)(this["PKMN_44"]));
            }
            set {
                this["PKMN_44"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_45 {
            get {
                return ((string)(this["PKMN_45"]));
            }
            set {
                this["PKMN_45"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_46 {
            get {
                return ((string)(this["PKMN_46"]));
            }
            set {
                this["PKMN_46"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_47 {
            get {
                return ((string)(this["PKMN_47"]));
            }
            set {
                this["PKMN_47"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_48 {
            get {
                return ((string)(this["PKMN_48"]));
            }
            set {
                this["PKMN_48"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_49 {
            get {
                return ((string)(this["PKMN_49"]));
            }
            set {
                this["PKMN_49"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_50 {
            get {
                return ((string)(this["PKMN_50"]));
            }
            set {
                this["PKMN_50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_51 {
            get {
                return ((string)(this["PKMN_51"]));
            }
            set {
                this["PKMN_51"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_52 {
            get {
                return ((string)(this["PKMN_52"]));
            }
            set {
                this["PKMN_52"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_53 {
            get {
                return ((string)(this["PKMN_53"]));
            }
            set {
                this["PKMN_53"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_54 {
            get {
                return ((string)(this["PKMN_54"]));
            }
            set {
                this["PKMN_54"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_55 {
            get {
                return ((string)(this["PKMN_55"]));
            }
            set {
                this["PKMN_55"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_56 {
            get {
                return ((string)(this["PKMN_56"]));
            }
            set {
                this["PKMN_56"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_57 {
            get {
                return ((string)(this["PKMN_57"]));
            }
            set {
                this["PKMN_57"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_58 {
            get {
                return ((string)(this["PKMN_58"]));
            }
            set {
                this["PKMN_58"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_59 {
            get {
                return ((string)(this["PKMN_59"]));
            }
            set {
                this["PKMN_59"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_60 {
            get {
                return ((string)(this["PKMN_60"]));
            }
            set {
                this["PKMN_60"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_61 {
            get {
                return ((string)(this["PKMN_61"]));
            }
            set {
                this["PKMN_61"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_62 {
            get {
                return ((string)(this["PKMN_62"]));
            }
            set {
                this["PKMN_62"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_63 {
            get {
                return ((string)(this["PKMN_63"]));
            }
            set {
                this["PKMN_63"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_64 {
            get {
                return ((string)(this["PKMN_64"]));
            }
            set {
                this["PKMN_64"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_65 {
            get {
                return ((string)(this["PKMN_65"]));
            }
            set {
                this["PKMN_65"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_66 {
            get {
                return ((string)(this["PKMN_66"]));
            }
            set {
                this["PKMN_66"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_67 {
            get {
                return ((string)(this["PKMN_67"]));
            }
            set {
                this["PKMN_67"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_68 {
            get {
                return ((string)(this["PKMN_68"]));
            }
            set {
                this["PKMN_68"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_69 {
            get {
                return ((string)(this["PKMN_69"]));
            }
            set {
                this["PKMN_69"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_70 {
            get {
                return ((string)(this["PKMN_70"]));
            }
            set {
                this["PKMN_70"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_71 {
            get {
                return ((string)(this["PKMN_71"]));
            }
            set {
                this["PKMN_71"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_72 {
            get {
                return ((string)(this["PKMN_72"]));
            }
            set {
                this["PKMN_72"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_73 {
            get {
                return ((string)(this["PKMN_73"]));
            }
            set {
                this["PKMN_73"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_74 {
            get {
                return ((string)(this["PKMN_74"]));
            }
            set {
                this["PKMN_74"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_75 {
            get {
                return ((string)(this["PKMN_75"]));
            }
            set {
                this["PKMN_75"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_76 {
            get {
                return ((string)(this["PKMN_76"]));
            }
            set {
                this["PKMN_76"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_77 {
            get {
                return ((string)(this["PKMN_77"]));
            }
            set {
                this["PKMN_77"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_78 {
            get {
                return ((string)(this["PKMN_78"]));
            }
            set {
                this["PKMN_78"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_79 {
            get {
                return ((string)(this["PKMN_79"]));
            }
            set {
                this["PKMN_79"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_80 {
            get {
                return ((string)(this["PKMN_80"]));
            }
            set {
                this["PKMN_80"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_81 {
            get {
                return ((string)(this["PKMN_81"]));
            }
            set {
                this["PKMN_81"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_82 {
            get {
                return ((string)(this["PKMN_82"]));
            }
            set {
                this["PKMN_82"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_83 {
            get {
                return ((string)(this["PKMN_83"]));
            }
            set {
                this["PKMN_83"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_84 {
            get {
                return ((string)(this["PKMN_84"]));
            }
            set {
                this["PKMN_84"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_85 {
            get {
                return ((string)(this["PKMN_85"]));
            }
            set {
                this["PKMN_85"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_86 {
            get {
                return ((string)(this["PKMN_86"]));
            }
            set {
                this["PKMN_86"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_87 {
            get {
                return ((string)(this["PKMN_87"]));
            }
            set {
                this["PKMN_87"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_88 {
            get {
                return ((string)(this["PKMN_88"]));
            }
            set {
                this["PKMN_88"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_89 {
            get {
                return ((string)(this["PKMN_89"]));
            }
            set {
                this["PKMN_89"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_90 {
            get {
                return ((string)(this["PKMN_90"]));
            }
            set {
                this["PKMN_90"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_91 {
            get {
                return ((string)(this["PKMN_91"]));
            }
            set {
                this["PKMN_91"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_92 {
            get {
                return ((string)(this["PKMN_92"]));
            }
            set {
                this["PKMN_92"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_93 {
            get {
                return ((string)(this["PKMN_93"]));
            }
            set {
                this["PKMN_93"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_94 {
            get {
                return ((string)(this["PKMN_94"]));
            }
            set {
                this["PKMN_94"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_95 {
            get {
                return ((string)(this["PKMN_95"]));
            }
            set {
                this["PKMN_95"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_96 {
            get {
                return ((string)(this["PKMN_96"]));
            }
            set {
                this["PKMN_96"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_97 {
            get {
                return ((string)(this["PKMN_97"]));
            }
            set {
                this["PKMN_97"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_98 {
            get {
                return ((string)(this["PKMN_98"]));
            }
            set {
                this["PKMN_98"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_99 {
            get {
                return ((string)(this["PKMN_99"]));
            }
            set {
                this["PKMN_99"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_100 {
            get {
                return ((string)(this["PKMN_100"]));
            }
            set {
                this["PKMN_100"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_101 {
            get {
                return ((string)(this["PKMN_101"]));
            }
            set {
                this["PKMN_101"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_102 {
            get {
                return ((string)(this["PKMN_102"]));
            }
            set {
                this["PKMN_102"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_103 {
            get {
                return ((string)(this["PKMN_103"]));
            }
            set {
                this["PKMN_103"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_104 {
            get {
                return ((string)(this["PKMN_104"]));
            }
            set {
                this["PKMN_104"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_105 {
            get {
                return ((string)(this["PKMN_105"]));
            }
            set {
                this["PKMN_105"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_106 {
            get {
                return ((string)(this["PKMN_106"]));
            }
            set {
                this["PKMN_106"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_107 {
            get {
                return ((string)(this["PKMN_107"]));
            }
            set {
                this["PKMN_107"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_108 {
            get {
                return ((string)(this["PKMN_108"]));
            }
            set {
                this["PKMN_108"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_109 {
            get {
                return ((string)(this["PKMN_109"]));
            }
            set {
                this["PKMN_109"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_110 {
            get {
                return ((string)(this["PKMN_110"]));
            }
            set {
                this["PKMN_110"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_111 {
            get {
                return ((string)(this["PKMN_111"]));
            }
            set {
                this["PKMN_111"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_112 {
            get {
                return ((string)(this["PKMN_112"]));
            }
            set {
                this["PKMN_112"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_113 {
            get {
                return ((string)(this["PKMN_113"]));
            }
            set {
                this["PKMN_113"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_114 {
            get {
                return ((string)(this["PKMN_114"]));
            }
            set {
                this["PKMN_114"] = value;
            }
        }
    }
}
