//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PokemonTCGApp.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class XYPromo : global::System.Configuration.ApplicationSettingsBase {
        
        private static XYPromo defaultInstance = ((XYPromo)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new XYPromo())));
        
        public static XYPromo Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_1 {
            get {
                return ((string)(this["PKMN_1"]));
            }
            set {
                this["PKMN_1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("false")]
        public string PKMN_0 {
            get {
                return ((string)(this["PKMN_0"]));
            }
            set {
                this["PKMN_0"] = value;
            }
        }
    }
}
